=== ChrisMcKenzie/gandhi/api/lib/schema/user.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": ["email", "password"],
  "properties": {
    "email": {
      "type": "string",
      "format": "email"
    },
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string",
      "default": ""
    },
    "password": {
      "type": "string"
    }
  }
}

=== ChrisMcKenzie/gandhi/test/fixtures/users.json
[
	{
		"id": "847e085b-df0e-4dc7-9cbf-d485d6e2de96",
		"password": "MXpmq49IiBhV/mqcmxx4NbCjbjFdqxknn4InfjzyHObiMA/opEmQNvL6n9cgQtwa8xPXzkUqk8jHIZLRCeOnIA==:V4forPzp/iVPNRf4oLI9e5zSCQwBfk7GqEi2vL8AhR5yfCesH2LYefEJZkOfsvuuOK7003cV1GsmiD4TRadAsA==:10000:sha1",
		"email": "dustin@ruelculture.com",
		"name": "Dustin Towery"
	}, {
		"id": "a5901ab6-bf17-49cd-981d-c25875aec8e9",
		"password": "LW78QorkVSGeyNoSijtsaR8128Tg0I6GbFLtqIGAqvEin3CbxqB/nDbeSIEKVA1m5m3IGP4SqilAwV+2w5SBkw==:ISvU0jPSWTb0nkO7yGlPMzUkaTIfMtDnJ1dAOH9CRda0R0QmsgAliEjdqPUXQsGMit8CMevYne7fpHKMCmWN5Q==:10000:sha1",
		"email": "mike.marcacci@gmail.com",
		"name": "Mike Marcacci"
	}
]
