=== ChrisMcKenzie/gandhi/lib/api/schemas/user.json
{
  "id": "user",
  "type":"object",
  "$schema": "http://json-schema.org/draft-04/schema",
  "required": [
    "password",
    "email"
  ],
  "additionalProperties": false,
  "properties":{
    "admin": {
      "type": "boolean",
      "default": false
    },
    "created": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "id": {
      "type":"string"
    },
    "name": {
      "type": "string",
      "default": ""
    },
    "password": {
      "type": "string"
    },
    "recovery_token": {
      "type": ["null","string"],
      "default": null
    },
    "updated": {
      "type": "string"
    }
  }
}

=== ChrisMcKenzie/gandhi/test/fixtures/db/users.json
[
  {
    "id": "72e7f9a1-614d-423e-8273-1194932f8718",
    "admin": false,
    "password": "c2NyeXB0AA8AAAAIAAAAAazOoRBesUNvcjIY6X2zSkOcY7LfHDj1ZNDK94tbdN3L6oG9bIi9jm4qsG2sAuEpffBpb8XuEATpReG5YIt1vL7dwlMttPrzGFq1EEKM4wbU",
    "recovery_token": null,
    "email": "michael.douglas@test.gandhi.io",
    "name": "Michael Douglas",
    "created": "Sat Jul 05 2014 21:35:40 GMT-0700 (PDT)",
    "updated": "Sat Jul 05 2014 21:35:40 GMT-0700 (PDT)"
  },
  {
    "id": "f6826282-1ffb-453d-8804-6b2921e6807f",
    "admin": false,
    "password": "c2NyeXB0AA4AAAAIAAAAAe6TqnGT43ChQ332QjkUCCHMYgXet95V5NlL3cw7xyZCf3P/OclO9vjqL1/QE+E42gKyCxWj2571hs/RrkBf+LCmpVIuhRIMhxYRUFwV9qW4",
    "recovery_token": null,
    "email": "matt.shafer@test.gandhi.io",
    "name": "Matt Shafer",
    "created": "Sat Jul 05 2014 21:35:40 GMT-0700 (PDT)",
    "updated": "Sat Jul 05 2014 21:35:40 GMT-0700 (PDT)"
  },
  {
    "id": "3cd2dc98-e280-4e72-a437-9a916d98b636",
    "admin": false,
    "password": "c2NyeXB0AA4AAAAIAAAAAfJfxQEzHBLEeh3eU5cNm3GkKHmAroIKbVQQl9KEFE7CmcbnNjKrAuahB0R5WrCjyGhV3ygzIaU2NhBxIScoQPG7wJP/N4nW91BNrPm4xue/",
    "recovery_token": null,
    "email": "eric.jensen@test.gandhi.io",
    "name": "Eric Jensen",
    "created": "Sat Jul 05 2014 21:35:40 GMT-0700 (PDT)",
    "updated": "Sat Jul 05 2014 21:35:40 GMT-0700 (PDT)"
  },
  {
    "id": "5a3cf444-9d87-4125-8026-2d5ffb834676",
    "admin": false,
    "password": "c2NyeXB0AA4AAAAIAAAAATZ/fO+WCFdWZ8CVN/tavTXX0WcFBCQDtzGZn6/nv0d6IBW8geom2/fQTVb4T0oPYd9Ze4baEKAWqU2PHU6oxBqhmj+kXf1CyBWTsCOUBFfP",
    "recovery_token": null,
    "email": "jon.ramos@test.gandhi.io",
    "name": "Jon Ramos",
    "created": "Sat Jul 05 2014 21:35:40 GMT-0700 (PDT)",
    "updated": "Sat Jul 05 2014 21:35:40 GMT-0700 (PDT)"
  },
  {
    "id": "82b08fd0-b93d-4169-a0bf-b25823077adb",
    "admin": false,
    "password": "c2NyeXB0AA4AAAAIAAAAAe/1UjL3qtgcQjKxswA1spbRkYInvpGu62YdiG2zfRjgUrxiI7KNWVBJkjlLEYUaSqputmF+RH+ugwQvu9UmZOU2cLMc5bNAxNA+ML/p1XXr",
    "recovery_token": null,
    "email": "mark.boerneke@test.gandhi.io",
    "name": "Mark Boerneke",
    "created": "Sat Jul 05 2014 21:35:40 GMT-0700 (PDT)",
    "updated": "Sat Jul 05 2014 21:35:40 GMT-0700 (PDT)"
  },
  {
    "id": "847e085b-df0e-4dc7-9cbf-d485d6e2de96",
    "admin": false,
    "password": "c2NyeXB0AA8AAAAIAAAAAfXCOXrKklbdOscJOZcTgvn94drsvqOu5tf/fc7/AV6RrUHMJr1HvcuNUD2gbCTXZ9RYPbpX9liyh5FoWb9nVzsUx+luLAX42wsm1ukOBLb5",
    "recovery_token": "eyJleHBpcmF0aW9uIjo5NDY2ODQ4MDAwMDAsInNlY3JldCI6Ik1weFlwMUpvd3RLN0tVaDIzZXcwK0NSSE1MdVpWSnZmMHQ1dG84UEtGNGVoYlNPTWZxbHNtLzJVWjBSc1ErR3BVK2ZaVHl1RklJRWo2czUvUTVWeEthZ1NhMG50VEVieE85M2FEUTdDQmZNUkwxUjhGRSsySFNwdTU3K2w1ajZmbnV2MDNvbkxDY2ltTUZ1UjZ6WFZvNVI0UnBvdDNMTTJjNlFRM1p0SzdRUFAwa2IvdDlXeVVocWZiMlhnVkh6K0srSUxTaXd5Z2dBU2ZpeHBYYlNGNXB0bTlIb3dtWlZYbUYwQnRmWnF6c09sNElyM1U3UVJaalFzdnVmUFJjMGQxV2tIVWNvcENLSnJma2JmMTFjanFRSGEydmFNSnJyQXVYZUZaeG9ZaEhtYWdFVXM1Q3NrMjAvR3ZUaXJmRXFPbHA4K0hiamRMWC83alZDR3JVQysxQT09In0=",
    "email": "dustin.towery@test.gandhi.io",
    "name": "Dustin Towery",
    "created": "Sat Jul 05 2014 21:35:40 GMT-0700 (PDT)",
    "updated": "Sat Jul 05 2014 21:35:40 GMT-0700 (PDT)"
  },
  {
    "id": "84fbaa78-54b0-42fc-9754-c9ea7dc24538",
    "admin": false,
    "password": "c2NyeXB0AA4AAAAIAAAAATA+dYEi/gYuTrBfkz2/kXbgLlh+H5d96Tdxab0+sZeupIuPLZG9SCY+FgW8OXUXL4KlJLOsKwoA3V2GYnfpp7Yt5OHDsfbHkDw+2XjL35T5",
    "recovery_token": "eyJleHBpcmF0aW9uIjozMjUzNTEyOTYwMDAwMCwic2VjcmV0IjoiWm1mazNuYjlndEw3c2hNQ1QrbjBGOTZ3cG50cHR3d0xNWVpnWjk0emlTaDgvQ1pqQmE0c3RJVDN2M2hDMWtqZ0QzcURmeWxtd1JBd1l5MVlybTlOQUtab3dCb1VWMTA3a1NmU0QvTFlFYThaUEdJckVoV3dxS2dYckdQZFp6Y2w5TUVLVEFJS1N1VVVwTUQ0aDU4bFlzVEZMSTZMQXBzaUlIN2hSbkJBRFVmWEk5b0JhTHo2NWppeTFheWhyU2xwdlZZYTZ5TkxOaUgvMFArTGNNM0FXaDJXZFFuN1BEQ3B0S0VyN0ZVV0pmNjFXU25SbmRJV0xodEcrUkQ5UXhaTkRvS1hSam05YXBJT2dzR0pIcnJGaXlzRVlhOEFibnd2ZjNNM0I5VzU2YXRrdjcwZnlocGx3U2lrcFo3bnNTVVpFMm1UWE1jb20zeHh5ektWdlE4MVVBPT0ifQ==",
    "email": "tim.marcacci@test.gandhi.io",
    "name": "Tim Marcacci",
    "created": "Sat Jul 05 2014 21:35:40 GMT-0700 (PDT)",
    "updated": "Sat Jul 05 2014 21:35:40 GMT-0700 (PDT)"
  },
  {
    "id": "a5901ab6-bf17-49cd-981d-c25875aec8e9",
    "admin": true,
    "password": "c2NyeXB0AA4AAAAIAAAAAXJUMPjPphkqlfeJ5X7Kx9EyRGQy/f74JOAS5zzEOVGsOL/Z2i/BjMz6rOn5pA2bIqyKcZfc8ipslSSZahvLteZ2ycnl3gSf2lqzdklnZyMA",
    "recovery_token": null,
    "email": "mike.marcacci@test.gandhi.io",
    "name": "Mike Marcacci",
    "created": "Sat Jul 05 2014 21:35:40 GMT-0700 (PDT)",
    "updated": "Sat Jul 05 2014 21:35:40 GMT-0700 (PDT)"
  }
]
